name: test

version: "3.8"

services:
  db-test:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}_test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm test
    environment:
      - NODE_ENV=test
      - CORS_URLS=http://frontend:3000
      - PORT=4000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-test:5432/${POSTGRES_DB}_test
    depends_on:
      db-test:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data_test:
